package com.example.model

object SampleMatchData {

    val defaultMatch = PadelMatch(
        id = 1L,
        title = "Финал Клуба: Тай-брейк 8:6",
        date = "29 сентября 2026, 21:30",
        scoreFinal = "8:6 (Тай-брейк)",
        durationMinutes = 48,
        location = "Padel Arena Center (Корт #3 WPT)",
        courtType = "Падел-корт 10x20м (Синее покрытие Mondo Supercourt XN)",
        totalShots = 24,
        avgSpeedKmh = 83.8f,
        maxSpeedKmh = 118.5f,
        inPercentage = 87.5f
    )

    val initialCalibrationPoints = listOf(
        CourtCalibrationPoint(
            id = 1,
            name = "Дальний левый угол",
            screenX = 0.25f,
            screenY = 0.20f,
            courtX = -5.0f,
            courtY = 10.0f
        ),
        CourtCalibrationPoint(
            id = 2,
            name = "Дальний правый угол",
            screenX = 0.75f,
            screenY = 0.20f,
            courtX = 5.0f,
            courtY = 10.0f
        ),
        CourtCalibrationPoint(
            id = 3,
            name = "Ближний правый угол",
            screenX = 0.92f,
            screenY = 0.88f,
            courtX = 5.0f,
            courtY = -10.0f
        ),
        CourtCalibrationPoint(
            id = 4,
            name = "Ближний левый угол",
            screenX = 0.08f,
            screenY = 0.88f,
            courtX = -5.0f,
            courtY = -10.0f
        )
    )

    val rallies = listOf(
        PadelRally(
            id = 1,
            matchId = 1L,
            rallyNumber = 1,
            server = "Ближний правый",
            score = "6:0",
            winnerTeam = "Near",
            shotCount = 3,
            durationSec = 6.2,
            summary = "Глубокая свеча в угол под заднее стекло, вынужденная ошибка соперника в сетку"
        ),
        PadelRally(
            id = 2,
            matchId = 1L,
            rallyNumber = 2,
            server = "Дальний левый",
            score = "6:1",
            winnerTeam = "Near",
            shotCount = 4,
            durationSec = 8.5,
            summary = "Плотная подача, перехват воллей с лёта у сетки в противоход"
        ),
        PadelRally(
            id = 3,
            matchId = 1L,
            rallyNumber = 3,
            server = "Дальний правый",
            score = "6:2",
            winnerTeam = "Near",
            shotCount = 3,
            durationSec = 5.8,
            summary = "Мощный смэш у сетки 112 км/ч с отскоком в диагональ — чистый виннер!"
        ),
        PadelRally(
            id = 4,
            matchId = 1L,
            rallyNumber = 4,
            server = "Ближний левый",
            score = "6:3",
            winnerTeam = "Far",
            shotCount = 3,
            durationSec = 4.2,
            summary = "Попытка драйва справа в угол, прямое касание дальнего стекла без пола (Аут)"
        ),
        PadelRally(
            id = 5,
            matchId = 1L,
            rallyNumber = 5,
            server = "Ближний правый",
            score = "7:5",
            winnerTeam = "Far",
            shotCount = 4,
            durationSec = 7.1,
            summary = "Острый диагональный кросс соперника в ближний угол, счёт 6:6"
        ),
        PadelRally(
            id = 6,
            matchId = 1L,
            rallyNumber = 6,
            server = "Ближний правый",
            score = "8:6",
            winnerTeam = "Near",
            shotCount = 4,
            durationSec = 8.0,
            summary = "Подача 78 км/ч, укороченный бэкхенд-воллей в левый угол — победное очко тай-брейка!"
        )
    )

    val defaultShots = listOf(
        PadelShot(
            id = 1,
            matchId = 1L,
            rallyId = 1,
            shotNumber = 1,
            timestampSec = 2.0,
            player = "Ближний левый (красная ракетка)",
            playerTeam = "Near",
            shotType = ShotType.LOB,
            bounceX = -3.8f,
            bounceY = 8.5f,
            playerPosX = -2.15f,
            playerPosY = -7.40f,
            speedKmh = 52.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:0",
            notes = "Глубокая свеча точно в дальний левый угол под заднее стекло"
        ),
        PadelShot(
            id = 2,
            matchId = 1L,
            rallyId = 1,
            shotNumber = 2,
            timestampSec = 4.0,
            player = "Дальний правый",
            playerTeam = "Far",
            shotType = ShotType.FOREHAND,
            bounceX = 3.2f,
            bounceY = 7.8f,
            playerPosX = 3.0f,
            playerPosY = 9.0f,
            speedKmh = 68.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:0",
            notes = "Возврат мяча после отскока от стекла"
        ),
        PadelShot(
            id = 3,
            matchId = 1L,
            rallyId = 1,
            shotNumber = 3,
            timestampSec = 6.0,
            player = "Дальний левый",
            playerTeam = "Far",
            shotType = ShotType.BACKHAND,
            bounceX = -0.5f,
            bounceY = 0.5f,
            playerPosX = -2.5f,
            playerPosY = 6.5f,
            speedKmh = 45.0f,
            outcome = ShotOutcome.NET,
            scoreSnapshot = "6:0",
            notes = "Вынужденная ошибка соперника в сетку"
        ),
        PadelShot(
            id = 4,
            matchId = 1L,
            rallyId = 2,
            shotNumber = 1,
            timestampSec = 13.0,
            player = "Дальний левый",
            playerTeam = "Far",
            shotType = ShotType.SERVE,
            bounceX = 2.5f,
            bounceY = -4.5f,
            playerPosX = -1.5f,
            playerPosY = 8.5f,
            speedKmh = 76.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:1",
            notes = "Подача по диагонали точно в ближний правый квадрат"
        ),
        PadelShot(
            id = 5,
            matchId = 1L,
            rallyId = 2,
            shotNumber = 2,
            timestampSec = 15.0,
            player = "Ближний правый (чёрная ракетка)",
            playerTeam = "Near",
            shotType = ShotType.FOREHAND,
            bounceX = 1.8f,
            bounceY = -2.0f,
            playerPosX = 2.0f,
            playerPosY = -6.5f,
            speedKmh = 72.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:1",
            notes = "Приём подачи по линии"
        ),
        PadelShot(
            id = 6,
            matchId = 1L,
            rallyId = 2,
            shotNumber = 3,
            timestampSec = 18.0,
            player = "Ближний правый (чёрная ракетка)",
            playerTeam = "Near",
            shotType = ShotType.VOLLEY,
            bounceX = -4.1f,
            bounceY = 8.8f,
            playerPosX = 1.5f,
            playerPosY = -1.2f,
            speedKmh = 88.0f,
            outcome = ShotOutcome.WINNER,
            scoreSnapshot = "6:1",
            notes = "Острый воллей с лёта у сетки в противоход сопернику"
        ),
        PadelShot(
            id = 7,
            matchId = 1L,
            rallyId = 3,
            shotNumber = 1,
            timestampSec = 26.0,
            player = "Дальний правый",
            playerTeam = "Far",
            shotType = ShotType.SERVE,
            bounceX = -2.8f,
            bounceY = -5.2f,
            playerPosX = 1.2f,
            playerPosY = 8.5f,
            speedKmh = 79.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:2",
            notes = "Подача в левый квадрат"
        ),
        PadelShot(
            id = 8,
            matchId = 1L,
            rallyId = 3,
            shotNumber = 2,
            timestampSec = 28.5,
            player = "Ближний левый",
            playerTeam = "Near",
            shotType = ShotType.BACKHAND,
            bounceX = -2.0f,
            bounceY = 3.5f,
            playerPosX = -3.2f,
            playerPosY = -6.0f,
            speedKmh = 65.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:2",
            notes = "Приём свечой в центр"
        ),
        PadelShot(
            id = 9,
            matchId = 1L,
            rallyId = 3,
            shotNumber = 3,
            timestampSec = 31.0,
            player = "Ближний левый",
            playerTeam = "Near",
            shotType = ShotType.SMASH,
            bounceX = 3.5f,
            bounceY = 6.8f,
            playerPosX = -0.5f,
            playerPosY = -1.5f,
            speedKmh = 112.0f,
            outcome = ShotOutcome.WINNER,
            scoreSnapshot = "6:2",
            notes = "Мощный смэш у сетки с отскоком в боковое стекло"
        ),
        PadelShot(
            id = 10,
            matchId = 1L,
            rallyId = 4,
            shotNumber = 1,
            timestampSec = 39.0,
            player = "Ближний левый",
            playerTeam = "Near",
            shotType = ShotType.SERVE,
            bounceX = 3.0f,
            bounceY = 4.8f,
            playerPosX = -1.8f,
            playerPosY = -8.2f,
            speedKmh = 80.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:3",
            notes = "Подача в правый квадрат"
        ),
        PadelShot(
            id = 11,
            matchId = 1L,
            rallyId = 4,
            shotNumber = 2,
            timestampSec = 42.0,
            player = "Ближний правый",
            playerTeam = "Near",
            shotType = ShotType.FOREHAND,
            bounceX = 1.2f,
            bounceY = 10.0f,
            playerPosX = 2.2f,
            playerPosY = -6.0f,
            speedKmh = 96.0f,
            outcome = ShotOutcome.OUT_WALL,
            scoreSnapshot = "6:3",
            notes = "Драйв справа прямо в дальнее стекло без касания корта — Аут"
        ),
        PadelShot(
            id = 12,
            matchId = 1L,
            rallyId = 5,
            shotNumber = 1,
            timestampSec = 46.0,
            player = "Ближний правый",
            playerTeam = "Near",
            shotType = ShotType.SERVE,
            bounceX = -2.6f,
            bounceY = 5.5f,
            playerPosX = 1.5f,
            playerPosY = -8.5f,
            speedKmh = 81.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "7:5",
            notes = "Подача при счёте 7:5"
        ),
        PadelShot(
            id = 13,
            matchId = 1L,
            rallyId = 5,
            shotNumber = 2,
            timestampSec = 48.0,
            player = "Дальний левый",
            playerTeam = "Far",
            shotType = ShotType.FOREHAND,
            bounceX = -1.5f,
            bounceY = 2.0f,
            playerPosX = -2.8f,
            playerPosY = 7.0f,
            speedKmh = 74.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "7:5",
            notes = "Ответ в центр корта"
        ),
        PadelShot(
            id = 14,
            matchId = 1L,
            rallyId = 5,
            shotNumber = 3,
            timestampSec = 50.0,
            player = "Дальний левый",
            playerTeam = "Far",
            shotType = ShotType.FOREHAND,
            bounceX = 4.3f,
            bounceY = -8.2f,
            playerPosX = -2.0f,
            playerPosY = 6.0f,
            speedKmh = 92.0f,
            outcome = ShotOutcome.WINNER,
            scoreSnapshot = "7:5",
            notes = "Кросс в ближний правый угол, сложный отскок — ошибка на возврате"
        ),
        PadelShot(
            id = 15,
            matchId = 1L,
            rallyId = 6,
            shotNumber = 1,
            timestampSec = 61.0,
            player = "Ближний правый",
            playerTeam = "Near",
            shotType = ShotType.SERVE,
            bounceX = 2.2f,
            bounceY = 5.1f,
            playerPosX = 1.8f,
            playerPosY = -8.5f,
            speedKmh = 78.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "8:6",
            notes = "Подача в правый квадрат"
        ),
        PadelShot(
            id = 16,
            matchId = 1L,
            rallyId = 6,
            shotNumber = 2,
            timestampSec = 63.5,
            player = "Дальний правый",
            playerTeam = "Far",
            shotType = ShotType.BACKHAND,
            bounceX = 1.0f,
            bounceY = -3.0f,
            playerPosX = 2.5f,
            playerPosY = 7.5f,
            speedKmh = 69.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "8:6",
            notes = "Низкий возврат по диагонали"
        ),
        PadelShot(
            id = 17,
            matchId = 1L,
            rallyId = 6,
            shotNumber = 3,
            timestampSec = 65.0,
            player = "Ближний левый",
            playerTeam = "Near",
            shotType = ShotType.VOLLEY,
            bounceX = -4.1f,
            bounceY = 7.9f,
            playerPosX = -1.2f,
            playerPosY = -1.0f,
            speedKmh = 84.0f,
            outcome = ShotOutcome.WINNER,
            scoreSnapshot = "8:6",
            notes = "Укороченный воллей в угол мимо соперника — победа в матче!"
        ),
        PadelShot(
            id = 18,
            matchId = 1L,
            rallyId = 2,
            shotNumber = 4,
            timestampSec = 20.0,
            player = "Дальний правый",
            playerTeam = "Far",
            shotType = ShotType.BANDEJA,
            bounceX = 3.8f,
            bounceY = -7.5f,
            playerPosX = 2.2f,
            playerPosY = 5.0f,
            speedKmh = 79.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "6:1",
            notes = "Резаная бандеха в правый угол"
        ),
        PadelShot(
            id = 19,
            matchId = 1L,
            rallyId = 3,
            shotNumber = 4,
            timestampSec = 34.0,
            player = "Ближний правый",
            playerTeam = "Near",
            shotType = ShotType.SMASH,
            bounceX = -2.9f,
            bounceY = 5.2f,
            playerPosX = 1.8f,
            playerPosY = -2.0f,
            speedKmh = 118.5f,
            outcome = ShotOutcome.WINNER,
            scoreSnapshot = "6:2",
            notes = "Максимальная зафиксированная скорость удара матча (118.5 км/ч)!"
        ),
        PadelShot(
            id = 20,
            matchId = 1L,
            rallyId = 5,
            shotNumber = 4,
            timestampSec = 52.0,
            player = "Дальний левый",
            playerTeam = "Far",
            shotType = ShotType.CHIQUITA,
            bounceX = -1.1f,
            bounceY = -1.5f,
            playerPosX = -3.0f,
            playerPosY = 7.5f,
            speedKmh = 62.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "7:5",
            notes = "Мягкая чикита точно под ноги игроку у сетки"
        ),
        PadelShot(
            id = 21,
            matchId = 1L,
            rallyId = 6,
            shotNumber = 4,
            timestampSec = 67.0,
            player = "Ближний правый",
            playerTeam = "Near",
            shotType = ShotType.BANDEJA,
            bounceX = 4.2f,
            bounceY = 8.1f,
            playerPosX = 2.0f,
            playerPosY = -3.2f,
            speedKmh = 86.0f,
            outcome = ShotOutcome.IN,
            scoreSnapshot = "8:6",
            notes = "Глубокая тактическая бандеха с сильным боковым вращением"
        )
    )
}
